name: Bacics in Ubuntu
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update package list
        run: sudo apt-get update
      - name: Install Fastfetch
        run: |
          wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.17.2/fastfetch-linux-amd64.deb
          sudo dpkg -i fastfetch-linux-amd64.deb
          sudo apt-get install -f
      - name: Run basic Ubuntu commands
        run: |
          echo "Current Dir:"
          pwd
          echo "Dir. Contents:"
          ls -la
          echo "Current User:"
          whoami
          echo "Sys Info:"
          uname -a
      - name: Run Fastfetch
        run: fastfetch
      - name: Imaginary Node
        env:
          NODE_VERSION: 20
        run: echo "Node.js version is $NODE_VERSION"
          
