name: Bacics in Ubuntu
on:
  push:
    branches:
      - main
env:
  NVM_DIR: /home/runner/.nvm
  NODE_VERSION: 20
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show Curent Shell
        run: echo $SHELL
      - name: Update package list
        run: sudo apt-get update
      - name: Install Fastfetch
        run: |
          wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.17.2/fastfetch-linux-amd64.deb
          sudo dpkg -i fastfetch-linux-amd64.deb
          sudo apt-get install -f
      - name: Run basic Ubuntu commands
        run: |
          echo "Current Dir:"
          pwd
          echo "Dir. Contents:"
          ls -la
          echo "Current User:"
          whoami
          echo "Sys Info:"
          uname -a
      - name: Run Fastfetch
        run: fastfetch
      - name: Imaginary Node
        env:
          TARGET_NODE_VERSION: 20
        run: |
          echo "The Target Node.js version is: $TARGET_NODE_VERSION" # | is for multiline block
      - name: Install NVM and Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          . $NVM_DIR/nvm.sh
          nvm install $NODE_VERSION
          nvm alias default $NODE_VERSION
          nvm use default
          echo 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $HOME/.bashrc
          source $HOME/.bashrc
          cat $HOME/.bashrc
      - name: Verify Node.js installation
        run: |
          cat $HOME/.bashrc
          which node
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"
